In [49]:
import pandas as pd
import numpy as np

In [50]:
patients_df = pd.read_csv('Patient_Data.csv.')
billing_df = pd.read_csv('Billing_Data.csv.')

In [51]:
patients_df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [52]:
billing_df.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [53]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [54]:
patients_df.describe()

        PatientID   BillAmount  ReceptionistID
count    6.000000     4.000000        6.000000
mean   102.666667  5925.000000        1.666667
std      1.632993  1192.686044        0.816497
min    101.000000  5000.000000        1.000000
25%    101.250000  5000.000000        1.000000
50%    102.500000  5600.000000        1.500000
75%    103.750000  6525.000000        2.000000
max    105.000000  7500.000000        3.000000

In [55]:
billing_cols = ['PatientID', 'Department', 'Doctor', 'BillAmount']
billing_clean = patients_df[billing_cols]

In [56]:
billing_clean.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [57]:
admin_cols = ['ReceptionistID', 'CheckInTime']
patients_df = patients_df.drop(columns=admin_cols)

In [58]:
patients_df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [59]:
dept_bill = patients_df.groupby('Department')['BillAmount'].sum().reset_index()

In [60]:
dept_bill.columns = ['Department', 'TotalBillAmount']

In [61]:
dept_bill

    Department  TotalBillAmount
0   Cardiology          16200.0
1  Dermatology              0.0
2    Neurology              0.0
3  Orthopedics           7500.0

In [62]:
patients_df = patients_df.drop_duplicates(subset='PatientID')

In [63]:
 patients_df.shape

(5, 5)

In [64]:
mean_val = patients_df['BillAmount'].mean()

In [65]:
patients_df['BillAmount'] = patients_df['BillAmount'].fillna(mean_val)

In [66]:
mean_val

np.float64(6233.333333333333)

In [67]:
final_merged = pd.merge(patients_df, billing_df, on='PatientID', how='left')

In [68]:
final_merged.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [69]:
new_patients = pd.DataFrame({
    'PatientID': [106, 107],
    'Name': ['Rahul', 'Sneha'],
    'Department': ['Cardiology', 'Orthopaedics'],
    'Doctor': ['Dr. Mehta', 'Dr. Rao'],
    'BillAmount': [20000, 15000],
    'InsuranceCovered': [2000, 1500],
    'FinalAmount': [18000, 13500]
})

In [70]:
final_merged = pd.concat([final_merged, new_patients], ignore_index=True)
final_merged.tail()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
5,106,Rahul,Cardiology,Dr. Mehta,20000.000000,2000,18000
6,107,Sneha,Orthopaedics,Dr. Rao,15000.000000,1500,13500

In [71]:
extra_cols = pd.DataFrame({
    'InsuranceCovered2': final_merged['BillAmount'] > 10000,
    'FinalAmount2': final_merged['BillAmount'] * 0.90
})

In [72]:
final_df = pd.concat([final_merged, extra_cols], axis=1)

In [73]:
final_df.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount,InsuranceCovered2,FinalAmount2
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000,False,4500.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500,False,5610.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000,False,6750.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200,False,5580.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000,False,5610.0

In [74]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PatientID          7 non-null      int64
 1   Name               7 non-null      object
 2   Department         7 non-null      object
 3   Doctor             7 non-null      object
 4   BillAmount         7 non-null      float64
 5   InsuranceCovered   7 non-null      int64
 6   FinalAmount        7 non-null      int64
 7   InsuranceCovered2  7 non-null      bool
 8   FinalAmount2       7 non-null      float64
dtypes: bool(1), float64(2), int64(3), object(3)
memory usage: 587.0+ bytes