Data Structures & Control Structures

Question1

In [3]:
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

numbers.append(60)
print("After append(60):", numbers)

numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

numbers.insert(2, 25)  
print("After insert(2, 25):", numbers)

numbers.remove(40)
print("After remove(40):", numbers)

popped_value = numbers.pop()  
print("After pop():", numbers, "| Popped value:", popped_value)

temp_list = numbers.copy()  
temp_list.clear()
print("After clear():", temp_list)

index_30 = numbers.index(30)
print("Index of 30:", index_30)

count_20 = numbers.count(20)
print("Count of 20:", count_20)

numbers.sort()
print("After sort():", numbers)

numbers.reverse()
print("After reverse():", numbers)

Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(): [10, 20, 25, 30, 50, 60, 70] | Popped value: 80
After clear(): []
Index of 30: 3
Count of 20: 1
After sort(): [10, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 10]

Question2

In [ ]:
students = ("Pratik", "Raj", "Prashant")
print("Original tuple:", students)

# Trying to change the second name
students[1] = "Dhairya"

Original tuple: ('Pratik', 'Raj', 'Prashant')

TypeError: 'tuple' object does not support item assignment

Tuple are immutable.Once a tuple is created, you cannot change, add, or remove elements from it.

Question3

In [12]:
num= {10, 20, 30, 20, 40, 10, 50}
print("Set:", num)

Set: {50, 20, 40, 10, 30}

Unordered:No guarantee of element order.
Unique elements only:Duplicates are automatically removed.

Question4

In [15]:
info = {
    "name": "Pratik",
    "age": 21,
    "city": "Pune"
}

print("Original dictionary:", info)


info["age"] = 22

info["email"] = "pratik@gmail.com"
print("Updated dictionary:", info)

Original dictionary: {'name': 'Pratik', 'age': 21, 'city': 'Pune'}
Updated dictionary: {'name': 'Pratik', 'age': 22, 'city': 'Pune', 'email': 'pratik@gmail.com'}

Question5

In [18]:
age = 22
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")

You are eligible to vote.

Question6

In [19]:
marks = 82
if marks >= 90:
    grade = "A"
elif 75 <= marks <= 89:
    grade = "B"
elif 50 <= marks <= 74:
    grade = "C"
else:
    grade = "F"  
print(f"Marks: {marks} | Grade: {grade}")

Marks: 82 | Grade: B

Question7

In [20]:
num = int(input("Enter a number: "))
if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

Enter a number:  23

The number is positive.
It is odd.

Numpy

Question8

In [22]:
import numpy as np

In [23]:
scalar = np.array(5)
print("Scalar:", scalar)
print("Shape:", scalar.shape)  

array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:", array_1d)
print("Shape:", array_1d.shape)

array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("\n2D Array:\n", array_2d)
print("Shape:", array_2d.shape)

Scalar: 5
Shape: ()

1D Array: [1 2 3 4 5]
Shape: (5,)

2D Array:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)

Question9

In [24]:
random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Integer Array:\n", random_array)

4x4 Random Integer Array:
 [[16 69 76 34]
 [15 89 53  8]
 [55 45 56 62]
 [51 15 76 48]]

Question10

In [25]:
import numpy as np
import pandas as pd
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])
print("2D NumPy Array:\n", array_2d)
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])
print("\nDataFrame:\n", df)

2D NumPy Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

DataFrame:
     A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

Pandas

Question11

In [26]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Pratik', 'Raj', 'Shyam', 'Ram', 'Sarthak', 'Suhel', 'Darshan', 'Prashu', 'Dhairya', 'Aditya'],
    'Age': [25, 30, 35, 40, 28, 33, 29, 31, 27, 26],
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Mumbai', 'Delhi', 'Kolkata', 'Chennai', 'Bangalore', 'Delhi'],
    'Salary': [50000, 60000, 70000, 80000, np.nan, 65000, 72000, 75000, 68000, 60000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
       Name  Age       City   Salary
0   Pratik   25     Mumbai  50000.0
1      Raj   30      Delhi  60000.0
2    Shyam   35  Bangalore  70000.0
3      Ram   40    Chennai  80000.0
4  Sarthak   28     Mumbai      NaN
5    Suhel   33      Delhi  65000.0
6  Darshan   29    Kolkata  72000.0
7   Prashu   31    Chennai  75000.0
8  Dhairya   27  Bangalore  68000.0
9   Aditya   26      Delhi  60000.0

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [28]:
df.describe()

             Age        Salary
count  10.000000      9.000000
mean   30.400000  66666.666667
std     4.575296   9069.178574
min    25.000000  50000.000000
25%    27.250000  60000.000000
50%    29.500000  68000.000000
75%    32.500000  72000.000000
max    40.000000  80000.000000

In [29]:
 df[['Name', 'City']]

      Name       City
0   Pratik     Mumbai
1      Raj      Delhi
2    Shyam  Bangalore
3      Ram    Chennai
4  Sarthak     Mumbai
5    Suhel      Delhi
6  Darshan    Kolkata
7   Prashu    Chennai
8  Dhairya  Bangalore
9   Aditya      Delhi

In [31]:
df_no_city = df.drop(columns=['City'])
df_no_city

      Name  Age   Salary
0   Pratik   25  50000.0
1      Raj   30  60000.0
2    Shyam   35  70000.0
3      Ram   40  80000.0
4  Sarthak   28      NaN
5    Suhel   33  65000.0
6  Darshan   29  72000.0
7   Prashu   31  75000.0
8  Dhairya   27  68000.0
9   Aditya   26  60000.0

In [34]:
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
df

      Name  Age       City        Salary
0   Pratik   25     Mumbai  50000.000000
1      Raj   30      Delhi  60000.000000
2    Shyam   35  Bangalore  70000.000000
3      Ram   40    Chennai  80000.000000
4  Sarthak   28     Mumbai  66666.666667
5    Suhel   33      Delhi  65000.000000
6  Darshan   29    Kolkata  72000.000000
7   Prashu   31    Chennai  75000.000000
8  Dhairya   27  Bangalore  68000.000000
9   Aditya   26      Delhi  60000.000000

In [35]:
df_no_duplicates = df.drop_duplicates()
df_no_duplicates

      Name  Age       City        Salary
0   Pratik   25     Mumbai  50000.000000
1      Raj   30      Delhi  60000.000000
2    Shyam   35  Bangalore  70000.000000
3      Ram   40    Chennai  80000.000000
4  Sarthak   28     Mumbai  66666.666667
5    Suhel   33      Delhi  65000.000000
6  Darshan   29    Kolkata  72000.000000
7   Prashu   31    Chennai  75000.000000
8  Dhairya   27  Bangalore  68000.000000
9   Aditya   26      Delhi  60000.000000